vich_uploader:
  db_driver: orm
  metadata:
    type: attribute

  mappings:
    sliders:
      uri_prefix: /uploads/images/sliders
      upload_destination: '%kernel.project_dir%/public/uploads/images/sliders'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    categories:
      uri_prefix: /uploads/images/categories
      upload_destination: '%kernel.project_dir%/public/uploads/images/categories'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    produits:
      uri_prefix: /uploads/images/produits
      upload_destination: '%kernel.project_dir%/public/uploads/images/produits'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
